name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install deps
        run: pip install pyinstaller flask

      - name: Build exe
        run: |
          mkdir build
          mkdir dist
          pyinstaller --onefile backend/app.py --clean --distpath dist --workpath build
